// <auto-generated />
using System;
using BillGeneratorSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillGeneratorSystem.Migrations
{
    [DbContext(typeof(BillGeneratorDbContext))]
    [Migration("20260404055122_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BillGeneratorSystem.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BillGeneratorSystem.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("BillGeneratorSystem.Models.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("BillGeneratorSystem.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatalogType = "entrance",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6702),
                            Description = "Full Price Entry",
                            IsActive = true,
                            Name = "Adult Ticket",
                            Price = 500m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6708)
                        },
                        new
                        {
                            Id = 2,
                            CatalogType = "entrance",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6716),
                            Description = "Children below 12 years",
                            IsActive = true,
                            Name = "Child Ticket",
                            Price = 250m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6717)
                        },
                        new
                        {
                            Id = 3,
                            CatalogType = "entrance",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6719),
                            Description = "Age 60+",
                            IsActive = true,
                            Name = "Senior Ticket",
                            Price = 300m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6719)
                        },
                        new
                        {
                            Id = 4,
                            CatalogType = "entrance",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6720),
                            Description = "Premium Access",
                            IsActive = true,
                            Name = "VIP Ticket",
                            Price = 1000m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6721)
                        },
                        new
                        {
                            Id = 5,
                            CatalogType = "donation",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6762),
                            Description = "₹100 Donation",
                            IsActive = true,
                            Name = "Small Donation",
                            Price = 100m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6762)
                        },
                        new
                        {
                            Id = 6,
                            CatalogType = "donation",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6764),
                            Description = "₹500 Donation",
                            IsActive = true,
                            Name = "Medium Donation",
                            Price = 500m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6765)
                        },
                        new
                        {
                            Id = 7,
                            CatalogType = "donation",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6766),
                            Description = "₹1000 Donation",
                            IsActive = true,
                            Name = "Large Donation",
                            Price = 1000m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6766)
                        },
                        new
                        {
                            Id = 8,
                            CatalogType = "product",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6787),
                            Description = "Event Merchandise",
                            IsActive = true,
                            Name = "T-Shirt",
                            Price = 300m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6788)
                        },
                        new
                        {
                            Id = 9,
                            CatalogType = "product",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6790),
                            Description = "Hot Beverage",
                            IsActive = true,
                            Name = "Coffee",
                            Price = 100m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6790)
                        },
                        new
                        {
                            Id = 10,
                            CatalogType = "product",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6792),
                            Description = "Reusable Bottle",
                            IsActive = true,
                            Name = "Water Bottle",
                            Price = 150m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6792)
                        },
                        new
                        {
                            Id = 11,
                            CatalogType = "product",
                            CreatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6793),
                            Description = "Assorted Snacks",
                            IsActive = true,
                            Name = "Snack Pack",
                            Price = 200m,
                            UpdatedAt = new DateTime(2026, 4, 4, 5, 51, 20, 957, DateTimeKind.Utc).AddTicks(6794)
                        });
                });

            modelBuilder.Entity("BillGeneratorSystem.Models.DailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SummaryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalBills")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DailySummaries");
                });

            modelBuilder.Entity("BillGeneratorSystem.Models.BillItem", b =>
                {
                    b.HasOne("BillGeneratorSystem.Models.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("BillGeneratorSystem.Models.Bill", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
